version: '3.9'

services:
  app:
    container_name: pat-app
    restart: always
    build:
      dockerfile: Dockerfile.local
    volumes:
      - ./:/var/www/html
    ports:
      - 8000:80
      - '3000:3000'
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - pgserver

  pgserver:
    image: postgres
    container_name: pg_pat
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - pg_data_pat:/var/lib/postgresql/data
      - ./docker/PGSQL:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg_data_pat:
    driver: local

